target = args[0]
task = args[1];

function codeStatus (code) {
	if (code == 1) {
		return "weakening";
	} else if (code == 2) {
		return "growing";
	} else if (code == 3) {
		return "hacking";
	}
}

function performWork() {
	// the work that is done here is the standard weaken, grow, and hack fuctions
	// that can be found in original template.
	if (hasRootAccess(target) == true) {
		tprint("running against " + target);
		if (codeStatus(task) == "weakening") {
			tprint("weakening");
			weaken(target);
		} else if (codeStatus(task) == "growing") {
			tprint("growing");
			grow(target);
		} else if (codeStatus(task) == "hacking") {
			tprint("hacking");
			var money = hack(target);
		}
	}
}

if (serverExists(target)) {
	performWork();
}
